[package]
    name = "lrgest"
    debug_build = true
    
[compiler]
    args = [
        "-fsanitize=address", 
        "-fsanitize-address-use-after-scope", 
        "-fsanitize=undefined",
        "-fsanitize=pointer-overflow"
    ]
    compiler = "gcc"

[linker]
    args = [
        "-fsanitize=address", 
        "-fsanitize-address-use-after-scope", 
        "-fsanitize=undefined",
        "-fsanitize=pointer-overflow"
    ]
[misc]
    static_analysis_enabled = true